apiVersion: apps/v1
kind: Deployment
metadata: 
  name: second-app
  labels:
    group: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
  template: 
    metadata: 
      labels: 
        app: second-app
    spec:
      containers:
      - name: second-app
        image: keorapetse159/kub-first-app:1
        livenessProbe:
          httpGet: 
            path: /
            port: 8080
          periodSeconds: 10
          initialDelaySeconds: 5
        ports:
        - containerPort: 8080
      # - name: ....
      #   image: ....