apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-app
  template:
    metadata:
      name: story-app
      labels:
        app: story-app
    spec:
      containers:
        - name: story-app
          image: keorapetse159/story-app:1 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          hostPath:
            path: /data
            type: DirectoryOrCreate
      restartPolicy: Always
      