apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story-app
  template:
    metadata:
      name: story-app
      labels:
        app: story-app
    spec:
      containers:
        - name: story-app
          image: keorapetse159/story-app:3 
          imagePullPolicy: IfNotPresent
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: story-env
                  key: folder
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
          # hostPath:
          #  path: /data
          # type: DirectoryOrCreate
      restartPolicy: Always
      