apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  labels:
    app: task-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      name: tasks
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: keorapetse159/task-api:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks
      