apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  labels:
    app: task-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      name: tasks
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      